#ifndef ERROR_H
#define ERROR_H

enum ERRORS_PROGRAMMES {
    ERRORS_PROGRAMMES_ONLY_ONE_MODE = -1,
    ERRORS_PROGRAMMES_PRECISE_ALGORITHM = -2,
    ERRORS_PROGRAMMES_TOO_MUCH_ARGS = -3,
    ERRORS_PROGRAMMES_NEED_MODE = -4,
    ERRORS_PROGRAMMES_FILE_INPUT_NOT_FOUND = -5,
};

void Errors_printf(enum ERRORS_PROGRAMMES);

#endif //ERROR_H